stages:
  extract:
    cmd: python src/extract_data/extract_data.py
    deps:
    - src/extract_data/extract_data.py
    - config.yaml
    outs:
    - data/raw/accidents_2023.csv
  prepare:
    cmd: python src/prepare_data/prepare_data.py
    deps:
    - data/raw/accidents_2023.csv
    - src/prepare_data/prepare_data.py
    - config.yaml
    outs:
    - data/processed/prepared_accidents_2023.csv
  models:
    cmd: python src/train_model/train_model.py
    deps:
    - data/processed/prepared_accidents_2023.csv
    - src/train_model/train_model.py
    - config.yaml
    outs:
    - models/best_model_2023.joblib
    - models/rf_model_2023.joblib
