name: Test of the ML Pipeline for Road Accidents

on:
  push:  
    branches:
      - main
  pull_request:  
    branches:
      - main
  workflow_dispatch:  

jobs:
  test-pipeline:
    name: Test Pipeline
    runs-on: ubuntu-latest

    steps:
      # Step 1: Clone the repository
      - name: Clone the repository
        uses: actions/checkout@v4

      # Step 2: Set up Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests beautifulsoup4 pyyaml scikit-learn joblib pytest fastapi uvicorn python-multipart mlflow

      # Step 4: Run the extract data script
      - name: Run extract_data.py
        run: |
          python src/extract_data/extract_data.py
          # Check if the raw data file was created
          if [ ! -f "data/raw/accidents_2023.csv" ]; then
            echo "Error: The file accidents_2023.csv was not created."
            exit 1
          fi

      # Step 5: Run the data preparation script
      - name: Run prepare_data.py
        run: |
          python src/prepare_data/prepare_data.py
          # Check if the prepared data file was created
          if [ ! -f "data/processed/prepared_accidents_2023.csv" ]; then
            echo "Error: The file prepared_accidents_2023.csv was not created."
            exit 1
          fi

      # Step 6: Run the model training script
      - name: Run train_model.py
        run: |
          python src/train_model/train_model.py
          # Check if the model file was saved
          if [ ! -f "models/rf_model_2023.joblib" ]; then
            echo "Error: The file rf_model_2023.joblib was not created."
            exit 1
          fi

      # Step 7: Run the tests
      - name: Run tests.py
        working-directory: ./tests
        run: |
          pytest

